Fixes

diff --git a/airback b/airback
--- a/airback
+++ b/airback
@@ -25,19 +25,6 @@ RSYNC_CMD="nice -n 20 rsync -${VERBOSITY}rultR --chmod=774"
 NMAP_CMD="nice -n 20 nmap "
 
 #
-# MAIN
-#
-
-# Check and source config file
-[ -r ${AIRBACK_CONFIG_FILE} ] || {
-	echo "Error config file not found: ${AIRBACK_CONFIG_FILE}"
-	exit 1
-}
-. ${AIRBACK_CONFIG_FILE}
-
-# todo check config variables...
-
-#
 # FUNCTIONS
 #
 # Args: IP PORT
@@ -155,6 +142,13 @@ function doBackup() {
 #
 # MAIN
 #
+
+# Check and source config file
+[ -r ${AIRBACK_CONFIG_FILE} ] || {
+	echo "Error config file not found: ${AIRBACK_CONFIG_FILE}"
+	exit 1
+}
+. ${AIRBACK_CONFIG_FILE}
 
 checkLocalMobileMountpointBase
 checkLocalBackupTargetBaseDir
