Fixes

diff --git a/airback b/airback
--- a/airback
+++ b/airback
@@ -107,12 +107,15 @@ function mountMobile() {
 		return 0
 	else
 		logInfo "Mobile is already mounted."
-		return 1
+		return 0
 	fi
 }
 
 function doBackup() {
-	mountMobile
+	mountMobile || {
+		echo "Error: mounting mobile failed."
+		return 1
+	}
 	cd ${LOCAL_MOBILE_MOUNTPOINT_BASE}
 
 #	set +e
@@ -265,8 +268,6 @@ function setVariableInConfigFile() {
 	logInfo "Setting new value for variable in config file:"
 	logInfo "Variable : ${1}"
 	logInfo "Value    : ${2}"
-#	SED_PARAM="s/${1}=.*$/${1}=\"${LOCAL_VALUE}\"/g"
-#	SED_PARAM="s#${1}=.*$#${1}=\"${2}\"#g"
 	SED_PARAM="s#${1}=.*#${1}=${2}#g"
 	logInfo "SED_PARAM=$SED_PARAM"
 	sed -i "$SED_PARAM" ${AIRBACK_CONFIG_FILE}
@@ -453,7 +454,7 @@ while true;do
 		RET_VAL=$?
 	done
 	logInfo "Server found."
-	doBackup
+	doBackup && echo "Backup successful"
 	logInfo "Backup done. Sleeping..."
 	[ "$RUN_AS_DAEMON" -eq 0 ] && {
 		logInfo "Not running in daemon mode. Exiting."
